### ISSUE TITLE
Create use-case test for pipeline

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/memory-map-plugin#15]
In order to release the new verson we need to test workflow job type with the usecase tester. Needed in order to release the change by @wbagdon .

https://github.com/Praqma/memory-map-plugin/blob/master/src/test/java/net/praqma/jenkins/usecases/UseCase.java

**Comment by buep** [comment]
Which use-cases will you test?

**Comment by MadsNielsen** [comment]
@buep There is only one currently. It's for GCC using GCC 4.8.2 on a hello world project using docker. It's a freestyle test. So if @Ordojan can produce an exact copy of that test, and get the same results we should be good. You agree?

**Comment by buep** [comment]
yes, great... agree. Do the same test using pipeline. 
Try to extract common parts if any, so we don't duplicate code between the two tests if they share some things.

**Comment by Ordojan** [comment]
blocked by #16
