### ISSUE TITLE
Could not find net.praqma:praqmajutils:0.1.34 (dependency problem)

### ISSUE THREAD

**Issue by ewelinawilkosz** [Praqma/memory-map-plugin#22]
When I test my job dsl with gradle (in build.gradle I have **testPlugins 'net.praqma:memory-map:2.2.0'**) I get

Could not resolve all dependencies for configuration ':testPlugins'.
> Could not find net.praqma:praqmajutils:0.1.34.
  Searched in the following locations:
      https://repo1.maven.org/maven2/net/praqma/praqmajutils/0.1.34/praqmajutils-0.1.34.pom
      https://repo1.maven.org/maven2/net/praqma/praqmajutils/0.1.34/praqmajutils-0.1.34.jar
      https://jcenter.bintray.com/net/praqma/praqmajutils/0.1.34/praqmajutils-0.1.34.pom
      https://jcenter.bintray.com/net/praqma/praqmajutils/0.1.34/praqmajutils-0.1.34.jar
      http://repo.jenkins-ci.org/releases/net/praqma/praqmajutils/0.1.34/praqmajutils-0.1.34.pom
      http://repo.jenkins-ci.org/releases/net/praqma/praqmajutils/0.1.34/praqmajutils-0.1.34.jar
  Required by:
      project : > net.praqma:memory-map:2.2.0

Can we make this dependency available again?

**Comment by buep** [comment]
The problem is the dependency is not properly released, but can be found in our own repository.

Can you as a work around fro now point the dependency to http://code.praqma.net/repo/maven/net/praqma/praqmajutils/ ?

Then we will fix the dependency problem in next release.

**Comment by ewelinawilkosz2** [comment]
Sure, it is working now with added repository

**Comment by patrickjmccarty** [comment]
This is still a problem. Moreover, the link given above as a workaround is now totally dead (Unknown host code.praqma.net). Try building this project without your local repo and you'll find other problems too.

**Comment by MadsNielsen** [comment]
@patrickjmccarty It should be fixed now :)

**Comment by patrickjmccarty** [comment]
@MadsNielsen Seems to build fine now. Thank you!
