### ISSUE TITLE
Review roadmap, architecture and blueprint

### ISSUE THREAD

**Issue by buep** [Praqma/memory-map-plugin#34]

**Comment by MadsNielsen** [comment]
Hi Bue, 

I took a look at your proposal, it looks OK to me. I like that the Blueprint leaves much of to the implmenter, to figure out the best approach to reach the desired state of a seperate library that can be reused outside of the plugin. 

I've added a couple of small changes to the blueprint, but it looks good.

**Comment by buep** [comment]
Thanks :-)
